
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.hikarinosanyousei.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;

import net.mcreator.hikarinosanyousei.item.XianshizhanspellcardItem;
import net.mcreator.hikarinosanyousei.item.WoodmushroomItem;
import net.mcreator.hikarinosanyousei.item.WatermoshroomItem;
import net.mcreator.hikarinosanyousei.item.ToumingItem;
import net.mcreator.hikarinosanyousei.item.TorchnewexItem;
import net.mcreator.hikarinosanyousei.item.TorchnewItem;
import net.mcreator.hikarinosanyousei.item.TeacupemptyitemItem;
import net.mcreator.hikarinosanyousei.item.SurpriseSpringshootingItem;
import net.mcreator.hikarinosanyousei.item.SungemstoneItem;
import net.mcreator.hikarinosanyousei.item.StarshootItem;
import net.mcreator.hikarinosanyousei.item.StargemstoneItem;
import net.mcreator.hikarinosanyousei.item.StardanmakuItem;
import net.mcreator.hikarinosanyousei.item.SpellcardstarlaserItem;
import net.mcreator.hikarinosanyousei.item.SpellcardshootingsapphireItem;
import net.mcreator.hikarinosanyousei.item.SpellcardlunaticraindanmakuItem;
import net.mcreator.hikarinosanyousei.item.SpellcardlunaticrainItem;
import net.mcreator.hikarinosanyousei.item.SpellcarddreamsealItem;
import net.mcreator.hikarinosanyousei.item.SpellcardSurpriseSpringItem;
import net.mcreator.hikarinosanyousei.item.SpellcardSunshineBlastItem;
import net.mcreator.hikarinosanyousei.item.SpellcardFlutteringSummerItem;
import net.mcreator.hikarinosanyousei.item.SpellcardFlashandStripeItem;
import net.mcreator.hikarinosanyousei.item.SpellcardFatalFlashItem;
import net.mcreator.hikarinosanyousei.item.Spellcard3Item;
import net.mcreator.hikarinosanyousei.item.Spellcard2Item;
import net.mcreator.hikarinosanyousei.item.SkillMarisastardustreverieItem;
import net.mcreator.hikarinosanyousei.item.SkillMarisaFinalsparkItem;
import net.mcreator.hikarinosanyousei.item.SkillMarisaDarkSparkItem;
import net.mcreator.hikarinosanyousei.item.ShootsapphireItem;
import net.mcreator.hikarinosanyousei.item.ShavedicecupfullItem;
import net.mcreator.hikarinosanyousei.item.ShavedicecupemptyItem;
import net.mcreator.hikarinosanyousei.item.ShanxingdanmuceshiItem;
import net.mcreator.hikarinosanyousei.item.SCMoonstillnessItem;
import net.mcreator.hikarinosanyousei.item.RoukankenqiaoItem;
import net.mcreator.hikarinosanyousei.item.RoukankenfengqiaoItem;
import net.mcreator.hikarinosanyousei.item.Roukankenfengqiao2Item;
import net.mcreator.hikarinosanyousei.item.Roukankenfengqiao1Item;
import net.mcreator.hikarinosanyousei.item.RoukankenItem;
import net.mcreator.hikarinosanyousei.item.PurnerItem;
import net.mcreator.hikarinosanyousei.item.PurificationRodItem;
import net.mcreator.hikarinosanyousei.item.PropertychangesreagentsItem;
import net.mcreator.hikarinosanyousei.item.PowerpotionItem;
import net.mcreator.hikarinosanyousei.item.PoetryraftstarItem;
import net.mcreator.hikarinosanyousei.item.PoetryraftlunaItem;
import net.mcreator.hikarinosanyousei.item.PoetryRaftsunItem;
import net.mcreator.hikarinosanyousei.item.PoetryRaftItem;
import net.mcreator.hikarinosanyousei.item.PoetryRaftEmptyItem;
import net.mcreator.hikarinosanyousei.item.PenItem;
import net.mcreator.hikarinosanyousei.item.NonDirectionalLaserspellcardItem;
import net.mcreator.hikarinosanyousei.item.MushroomsoybeanItem;
import net.mcreator.hikarinosanyousei.item.MushroomredItem;
import net.mcreator.hikarinosanyousei.item.MushroommanaItem;
import net.mcreator.hikarinosanyousei.item.MushroombigItem;
import net.mcreator.hikarinosanyousei.item.MudmushroomItem;
import net.mcreator.hikarinosanyousei.item.MinihakkeromastersparkItem;
import net.mcreator.hikarinosanyousei.item.MinihakkeroblazingstarItem;
import net.mcreator.hikarinosanyousei.item.MinihakkeroFinalSparkItem;
import net.mcreator.hikarinosanyousei.item.MinihakkeroDrakSparkItem;
import net.mcreator.hikarinosanyousei.item.MinihakkeroDarkSparkItem;
import net.mcreator.hikarinosanyousei.item.MinihakeromasterSparkItem;
import net.mcreator.hikarinosanyousei.item.MiniHakeeroItem;
import net.mcreator.hikarinosanyousei.item.MilkemptyItem;
import net.mcreator.hikarinosanyousei.item.MilkItem;
import net.mcreator.hikarinosanyousei.item.MeleeskillcardItem;
import net.mcreator.hikarinosanyousei.item.MasterSparkspellcardItem;
import net.mcreator.hikarinosanyousei.item.MarisasDanmakuNotesItem;
import net.mcreator.hikarinosanyousei.item.ManapowerpotionItem;
import net.mcreator.hikarinosanyousei.item.ManapotionemptyItem;
import net.mcreator.hikarinosanyousei.item.ManaPotionItem;
import net.mcreator.hikarinosanyousei.item.MajikaruSanpaisairiyouBomushootItem;
import net.mcreator.hikarinosanyousei.item.MajikaruSanpaisairiyouBomuItem;
import net.mcreator.hikarinosanyousei.item.MagicbroomItem;
import net.mcreator.hikarinosanyousei.item.LunagemstoneItem;
import net.mcreator.hikarinosanyousei.item.LoukankenItem;
import net.mcreator.hikarinosanyousei.item.LasernormlItem;
import net.mcreator.hikarinosanyousei.item.JiupingitemItem;
import net.mcreator.hikarinosanyousei.item.JiupingemtpyitemItem;
import net.mcreator.hikarinosanyousei.item.JianshengroukankenItem;
import net.mcreator.hikarinosanyousei.item.InsertaSunnymilkbottleintoacherryblossombranchItem;
import net.mcreator.hikarinosanyousei.item.InsertaSunnymilkbottleintoabloomingcherryblossombranchItem;
import net.mcreator.hikarinosanyousei.item.HakuroukenqiaoItem;
import net.mcreator.hikarinosanyousei.item.HakuroukennewItem;
import net.mcreator.hikarinosanyousei.item.Hakuroukenfengqiao3Item;
import net.mcreator.hikarinosanyousei.item.Hakuroukenfengqiao2Item;
import net.mcreator.hikarinosanyousei.item.Hakuroukenfengqiao1Item;
import net.mcreator.hikarinosanyousei.item.HakuroukenItem;
import net.mcreator.hikarinosanyousei.item.GoldmoshroomItem;
import net.mcreator.hikarinosanyousei.item.GarzeItem;
import net.mcreator.hikarinosanyousei.item.FluorescentlampoffItem;
import net.mcreator.hikarinosanyousei.item.FluorescentlampItem;
import net.mcreator.hikarinosanyousei.item.FlowermagicbookItem;
import net.mcreator.hikarinosanyousei.item.FiremoshroomItem;
import net.mcreator.hikarinosanyousei.item.ErrPotionItem;
import net.mcreator.hikarinosanyousei.item.EarthLightRayspellcardItem;
import net.mcreator.hikarinosanyousei.item.DefendItem;
import net.mcreator.hikarinosanyousei.item.Danmakutest1Item;
import net.mcreator.hikarinosanyousei.item.DanmaguItem;
import net.mcreator.hikarinosanyousei.item.CupteaitemItem;
import net.mcreator.hikarinosanyousei.item.CupjiuitemItem;
import net.mcreator.hikarinosanyousei.item.CupemptyitemItem;
import net.mcreator.hikarinosanyousei.item.CrinozhaohuanItem;
import net.mcreator.hikarinosanyousei.item.ConfigsayItem;
import net.mcreator.hikarinosanyousei.item.ConfigmpItem;
import net.mcreator.hikarinosanyousei.item.ColdSprinklerSpellcardItem;
import net.mcreator.hikarinosanyousei.item.ColdSprinklerShootingItem;
import net.mcreator.hikarinosanyousei.item.CoffeemilkItem;
import net.mcreator.hikarinosanyousei.item.CoffeeemptyItem;
import net.mcreator.hikarinosanyousei.item.CoffeeItem;
import net.mcreator.hikarinosanyousei.item.CirnoIceItem;
import net.mcreator.hikarinosanyousei.item.CherryblossombranchesItem;
import net.mcreator.hikarinosanyousei.item.CacoonItem;
import net.mcreator.hikarinosanyousei.item.BurnedfriedeggItem;
import net.mcreator.hikarinosanyousei.item.BloomingcherryblossombranchesItem;
import net.mcreator.hikarinosanyousei.item.BiglaserItem;
import net.mcreator.hikarinosanyousei.item.AmuletItem;
import net.mcreator.hikarinosanyousei.item.Amulet3Item;
import net.mcreator.hikarinosanyousei.item.Amulet2Item;
import net.mcreator.hikarinosanyousei.item.Amulet1Item;
import net.mcreator.hikarinosanyousei.HikariNoSanyouseiMod;

public class HikariNoSanyouseiModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, HikariNoSanyouseiMod.MODID);
	public static final RegistryObject<Item> SUNGEMSTONE = REGISTRY.register("sungemstone", () -> new SungemstoneItem());
	public static final RegistryObject<Item> LUNAGEMSTONE = REGISTRY.register("lunagemstone", () -> new LunagemstoneItem());
	public static final RegistryObject<Item> STARGEMSTONE = REGISTRY.register("stargemstone", () -> new StargemstoneItem());
	public static final RegistryObject<Item> CIRNO_ICE = REGISTRY.register("cirno_ice", () -> new CirnoIceItem());
	public static final RegistryObject<Item> BLOOMINGCHERRYBLOSSOMBRANCHES = REGISTRY.register("bloomingcherryblossombranches", () -> new BloomingcherryblossombranchesItem());
	public static final RegistryObject<Item> CACOON = REGISTRY.register("cacoon", () -> new CacoonItem());
	public static final RegistryObject<Item> TORCHNEWEX = REGISTRY.register("torchnewex", () -> new TorchnewexItem());
	public static final RegistryObject<Item> TORCHNEW = REGISTRY.register("torchnew", () -> new TorchnewItem());
	public static final RegistryObject<Item> CUPEMPTYITEM = REGISTRY.register("cupemptyitem", () -> new CupemptyitemItem());
	public static final RegistryObject<Item> CUPTEAITEM = REGISTRY.register("cupteaitem", () -> new CupteaitemItem());
	public static final RegistryObject<Item> CUPJIUITEM = REGISTRY.register("cupjiuitem", () -> new CupjiuitemItem());
	public static final RegistryObject<Item> JIUPINGITEM = REGISTRY.register("jiupingitem", () -> new JiupingitemItem());
	public static final RegistryObject<Item> TEACUP = block(HikariNoSanyouseiModBlocks.TEACUP, HikariNoSanyouseiModTabs.TAB_HIKARISANYOUSEI);
	public static final RegistryObject<Item> TEACUPEMPTYITEM = REGISTRY.register("teacupemptyitem", () -> new TeacupemptyitemItem());
	public static final RegistryObject<Item> JIUPINGEMTPYITEM = REGISTRY.register("jiupingemtpyitem", () -> new JiupingemtpyitemItem());
	public static final RegistryObject<Item> PEN = REGISTRY.register("pen", () -> new PenItem());
	public static final RegistryObject<Item> POETRY_RAFT_EMPTY = REGISTRY.register("poetry_raft_empty", () -> new PoetryRaftEmptyItem());
	public static final RegistryObject<Item> POETRY_RAFT_STAR = REGISTRY.register("poetry_raft_star", () -> new PoetryRaftItem());
	public static final RegistryObject<Item> SHAVEDICECUPEMPTY = REGISTRY.register("shavedicecupempty", () -> new ShavedicecupemptyItem());
	public static final RegistryObject<Item> SHAVEDICECUPFULL = REGISTRY.register("shavedicecupfull", () -> new ShavedicecupfullItem());
	public static final RegistryObject<Item> EHAVEDICECUPBLOCK = block(HikariNoSanyouseiModBlocks.EHAVEDICECUPBLOCK, HikariNoSanyouseiModTabs.TAB_HIKARISANYOUSEI);
	public static final RegistryObject<Item> SPELLCARD_2 = REGISTRY.register("spellcard_2", () -> new Spellcard2Item());
	public static final RegistryObject<Item> SPELLCARD_3 = REGISTRY.register("spellcard_3", () -> new Spellcard3Item());
	public static final RegistryObject<Item> POETRY_RAFTSUN = REGISTRY.register("poetry_raftsun", () -> new PoetryRaftsunItem());
	public static final RegistryObject<Item> POETRYRAFTLUNA = REGISTRY.register("poetryraftluna", () -> new PoetryraftlunaItem());
	public static final RegistryObject<Item> POETRYRAFTSTAR = REGISTRY.register("poetryraftstar", () -> new PoetryraftstarItem());
	public static final RegistryObject<Item> PURNER = REGISTRY.register("purner", () -> new PurnerItem());
	public static final RegistryObject<Item> MUSHROOMPOTTED = block(HikariNoSanyouseiModBlocks.MUSHROOMPOTTED, HikariNoSanyouseiModTabs.TAB_HIKARISANYOUSEI);
	public static final RegistryObject<Item> MUSHROOMPOTTEDEMPTY = block(HikariNoSanyouseiModBlocks.MUSHROOMPOTTEDEMPTY, HikariNoSanyouseiModTabs.TAB_HIKARISANYOUSEI);
	public static final RegistryObject<Item> MUSHROOMRED = REGISTRY.register("mushroomred", () -> new MushroomredItem());
	public static final RegistryObject<Item> MUSHROOMSOYBEAN = REGISTRY.register("mushroomsoybean", () -> new MushroomsoybeanItem());
	public static final RegistryObject<Item> MUSHROOMBIG = REGISTRY.register("mushroombig", () -> new MushroombigItem());
	public static final RegistryObject<Item> SUNNYMILKEMPTY = REGISTRY.register("sunnymilkempty", () -> new MilkemptyItem());
	public static final RegistryObject<Item> SUNNYMILK = REGISTRY.register("sunnymilk", () -> new MilkItem());
	public static final RegistryObject<Item> COFFEEEMPTY = REGISTRY.register("coffeeempty", () -> new CoffeeemptyItem());
	public static final RegistryObject<Item> COFFEE = REGISTRY.register("coffee", () -> new CoffeeItem());
	public static final RegistryObject<Item> COFFEEMILK = REGISTRY.register("coffeemilk", () -> new CoffeemilkItem());
	public static final RegistryObject<Item> FLUORESCENTLAMP = REGISTRY.register("fluorescentlamp", () -> new FluorescentlampItem());
	public static final RegistryObject<Item> FLUORESCENTLAMPOFF = REGISTRY.register("fluorescentlampoff", () -> new FluorescentlampoffItem());
	public static final RegistryObject<Item> CHERRYBLOSSOMBRANCHES = REGISTRY.register("cherryblossombranches", () -> new CherryblossombranchesItem());
	public static final RegistryObject<Item> INSERTA_SUNNYMILKBOTTLEINTOACHERRYBLOSSOMBRANCH = REGISTRY.register("inserta_sunnymilkbottleintoacherryblossombranch", () -> new InsertaSunnymilkbottleintoacherryblossombranchItem());
	public static final RegistryObject<Item> INSERTA_SUNNYMILKBOTTLEINTOABLOOMINGCHERRYBLOSSOMBRANCH = REGISTRY.register("inserta_sunnymilkbottleintoabloomingcherryblossombranch",
			() -> new InsertaSunnymilkbottleintoabloomingcherryblossombranchItem());
	public static final RegistryObject<Item> SPELLCARD_FATAL_FLASH = REGISTRY.register("spellcard_fatal_flash", () -> new SpellcardFatalFlashItem());
	public static final RegistryObject<Item> SPELLCARDLUNATICRAIN = REGISTRY.register("spellcardlunaticrain", () -> new SpellcardlunaticrainItem());
	public static final RegistryObject<Item> SPELLCARDTWINKLESAPPHIRE = REGISTRY.register("spellcardtwinklesapphire", () -> new SpellcardshootingsapphireItem());
	public static final RegistryObject<Item> SPELLCARDSTARLASER = REGISTRY.register("spellcardstarlaser", () -> new SpellcardstarlaserItem());
	public static final RegistryObject<Item> SPELLCARD_SUNSHINE_BLAST = REGISTRY.register("spellcard_sunshine_blast", () -> new SpellcardSunshineBlastItem());
	public static final RegistryObject<Item> SC_MOONSTILLNESS = REGISTRY.register("sc_moonstillness", () -> new SCMoonstillnessItem());
	public static final RegistryObject<Item> DANMAGU = REGISTRY.register("danmagu", () -> new DanmaguItem());
	public static final RegistryObject<Item> COLD_SPRINKLER_SPELLCARD = REGISTRY.register("cold_sprinkler_spellcard", () -> new ColdSprinklerSpellcardItem());
	public static final RegistryObject<Item> GARZE = REGISTRY.register("garze", () -> new GarzeItem());
	public static final RegistryObject<Item> CRINOZHAOHUAN = REGISTRY.register("crinozhaohuan", () -> new CrinozhaohuanItem());
	public static final RegistryObject<Item> DEFEND = REGISTRY.register("defend", () -> new DefendItem());
	public static final RegistryObject<Item> MASTER_SPARKSPELLCARD = REGISTRY.register("master_sparkspellcard", () -> new MasterSparkspellcardItem());
	public static final RegistryObject<Item> ROUKANKENFENGQIAO = REGISTRY.register("roukankenfengqiao", () -> new RoukankenfengqiaoItem());
	public static final RegistryObject<Item> HAKUROUKENFENGQIAO_3 = REGISTRY.register("hakuroukenfengqiao_3", () -> new Hakuroukenfengqiao3Item());
	public static final RegistryObject<Item> XIANSHIZHANSPELLCARD = REGISTRY.register("xianshizhanspellcard", () -> new XianshizhanspellcardItem());
	public static final RegistryObject<Item> SPELLCARD_SURPRISE_SPRING = REGISTRY.register("spellcard_surprise_spring", () -> new SpellcardSurpriseSpringItem());
	public static final RegistryObject<Item> SPELLCARD_FLUTTERING_SUMMER = REGISTRY.register("spellcard_fluttering_summer", () -> new SpellcardFlutteringSummerItem());
	public static final RegistryObject<Item> SPELLCARD_FLASHAND_STRIPE = REGISTRY.register("spellcard_flashand_stripe", () -> new SpellcardFlashandStripeItem());
	public static final RegistryObject<Item> SHOOTSAPPHIRE = REGISTRY.register("shootsapphire", () -> new ShootsapphireItem());
	public static final RegistryObject<Item> STARSHOOT = REGISTRY.register("starshoot", () -> new StarshootItem());
	public static final RegistryObject<Item> CUPEMPTYBLOCK = block(HikariNoSanyouseiModBlocks.CUPEMPTYBLOCK, HikariNoSanyouseiModTabs.TAB_HIKARISANYOUSEITEST);
	public static final RegistryObject<Item> JIUPINGEMPTYBLOCK = block(HikariNoSanyouseiModBlocks.JIUPINGEMPTYBLOCK, HikariNoSanyouseiModTabs.TAB_HIKARISANYOUSEITEST);
	public static final RegistryObject<Item> JIUPINGFULLBLOCK = block(HikariNoSanyouseiModBlocks.JIUPINGFULLBLOCK, HikariNoSanyouseiModTabs.TAB_HIKARISANYOUSEITEST);
	public static final RegistryObject<Item> TEACUPEMPTY = block(HikariNoSanyouseiModBlocks.TEACUPEMPTY, HikariNoSanyouseiModTabs.TAB_HIKARISANYOUSEITEST);
	public static final RegistryObject<Item> MINIHAKEROMASTER_SPARK = REGISTRY.register("minihakeromaster_spark", () -> new MinihakeromasterSparkItem());
	public static final RegistryObject<Item> COLD_SPRINKLER_SHOOTING = REGISTRY.register("cold_sprinkler_shooting", () -> new ColdSprinklerShootingItem());
	public static final RegistryObject<Item> FLOWERMAGICBOOK = REGISTRY.register("flowermagicbook", () -> new FlowermagicbookItem());
	public static final RegistryObject<Item> MINIHAKKEROBLAZINGSTAR = REGISTRY.register("minihakkeroblazingstar", () -> new MinihakkeroblazingstarItem());
	public static final RegistryObject<Item> SURPRISE_SPRINGSHOOTING = REGISTRY.register("surprise_springshooting", () -> new SurpriseSpringshootingItem());
	public static final RegistryObject<Item> MINI_HAKEERO = REGISTRY.register("mini_hakeero", () -> new MiniHakeeroItem());
	public static final RegistryObject<Item> MAGICBROOM = REGISTRY.register("magicbroom", () -> new MagicbroomItem());
	public static final RegistryObject<Item> MELEESKILLCARD = REGISTRY.register("meleeskillcard", () -> new MeleeskillcardItem());
	public static final RegistryObject<Item> TOUMING = REGISTRY.register("touming", () -> new ToumingItem());
	public static final RegistryObject<Item> ROUKANKEN = REGISTRY.register("roukanken", () -> new RoukankenItem());
	public static final RegistryObject<Item> ROUKANKENFENGQIAO_1 = REGISTRY.register("roukankenfengqiao_1", () -> new Roukankenfengqiao1Item());
	public static final RegistryObject<Item> ROUKANKENFENGQIAO_2 = REGISTRY.register("roukankenfengqiao_2", () -> new Roukankenfengqiao2Item());
	public static final RegistryObject<Item> ROUKANKENQIAO = REGISTRY.register("roukankenqiao", () -> new RoukankenqiaoItem());
	public static final RegistryObject<Item> HAKUROUKEN = REGISTRY.register("hakurouken", () -> new HakuroukenItem());
	public static final RegistryObject<Item> HAKUROUKENFENGQIAO_1 = REGISTRY.register("hakuroukenfengqiao_1", () -> new Hakuroukenfengqiao1Item());
	public static final RegistryObject<Item> HAKUROUKENFENGQIAO_2 = REGISTRY.register("hakuroukenfengqiao_2", () -> new Hakuroukenfengqiao2Item());
	public static final RegistryObject<Item> HAKUROUKENQIAO = REGISTRY.register("hakuroukenqiao", () -> new HakuroukenqiaoItem());
	public static final RegistryObject<Item> MANAPOTIONEMPTY = REGISTRY.register("manapotionempty", () -> new ManapotionemptyItem());
	public static final RegistryObject<Item> MANA_POTION = REGISTRY.register("mana_potion", () -> new ManaPotionItem());
	public static final RegistryObject<Item> MAJIKARU_SANPAISAIRIYOU_BOMU = REGISTRY.register("majikaru_sanpaisairiyou_bomu", () -> new MajikaruSanpaisairiyouBomuItem());
	public static final RegistryObject<Item> MAJIKARU_SANPAISAIRIYOU_BOMUSHOOT = REGISTRY.register("majikaru_sanpaisairiyou_bomushoot", () -> new MajikaruSanpaisairiyouBomushootItem());
	public static final RegistryObject<Item> MUSHROOMMANA = REGISTRY.register("mushroommana", () -> new MushroommanaItem());
	public static final RegistryObject<Item> MAGICPOT = block(HikariNoSanyouseiModBlocks.MAGICPOT, HikariNoSanyouseiModTabs.TAB_POTION);
	public static final RegistryObject<Item> MAGICPOTWATER = block(HikariNoSanyouseiModBlocks.MAGICPOTWATER, HikariNoSanyouseiModTabs.TAB_POTION);
	public static final RegistryObject<Item> ERR_POTION = REGISTRY.register("err_potion", () -> new ErrPotionItem());
	public static final RegistryObject<Item> POTIONMIXER = block(HikariNoSanyouseiModBlocks.POTIONMIXER, HikariNoSanyouseiModTabs.TAB_POTION);
	public static final RegistryObject<Item> POWERPOTION = REGISTRY.register("powerpotion", () -> new PowerpotionItem());
	public static final RegistryObject<Item> PROPERTYCHANGESREAGENTS = REGISTRY.register("propertychangesreagents", () -> new PropertychangesreagentsItem());
	public static final RegistryObject<Item> MANAPOWERPOTION = REGISTRY.register("manapowerpotion", () -> new ManapowerpotionItem());
	public static final RegistryObject<Item> MINIHAKKEROMASTERSPARK = REGISTRY.register("minihakkeromasterspark", () -> new MinihakkeromastersparkItem());
	public static final RegistryObject<Item> JIANSHENGROUKANKEN = REGISTRY.register("jianshengroukanken", () -> new JianshengroukankenItem());
	public static final RegistryObject<Item> FIREMOSHROOM = REGISTRY.register("firemoshroom", () -> new FiremoshroomItem());
	public static final RegistryObject<Item> WATERMOSHROOM = REGISTRY.register("watermoshroom", () -> new WatermoshroomItem());
	public static final RegistryObject<Item> GOLDMOSHROOM = REGISTRY.register("goldmoshroom", () -> new GoldmoshroomItem());
	public static final RegistryObject<Item> MUDMUSHROOM = REGISTRY.register("mudmushroom", () -> new MudmushroomItem());
	public static final RegistryObject<Item> WOODMUSHROOM = REGISTRY.register("woodmushroom", () -> new WoodmushroomItem());
	public static final RegistryObject<Item> STARDANMAKU = REGISTRY.register("stardanmaku", () -> new StardanmakuItem());
	public static final RegistryObject<Item> SPELLCARDDREAMSEAL = REGISTRY.register("spellcarddreamseal", () -> new SpellcarddreamsealItem());
	public static final RegistryObject<Item> AMULET = REGISTRY.register("amulet", () -> new AmuletItem());
	public static final RegistryObject<Item> AMULET_1 = REGISTRY.register("amulet_1", () -> new Amulet1Item());
	public static final RegistryObject<Item> AMULET_2 = REGISTRY.register("amulet_2", () -> new Amulet2Item());
	public static final RegistryObject<Item> AMULET_3 = REGISTRY.register("amulet_3", () -> new Amulet3Item());
	public static final RegistryObject<Item> PURIFICATION_ROD = REGISTRY.register("purification_rod", () -> new PurificationRodItem());
	public static final RegistryObject<Item> EARTH_LIGHT_RAYSPELLCARD = REGISTRY.register("earth_light_rayspellcard", () -> new EarthLightRayspellcardItem());
	public static final RegistryObject<Item> NON_DIRECTIONAL_LASERSPELLCARD = REGISTRY.register("non_directional_laserspellcard", () -> new NonDirectionalLaserspellcardItem());
	public static final RegistryObject<Item> CONFIGSAY = REGISTRY.register("configsay", () -> new ConfigsayItem());
	public static final RegistryObject<Item> CIRNO_SPAWN_EGG = REGISTRY.register("cirno_spawn_egg", () -> new ForgeSpawnEggItem(HikariNoSanyouseiModEntities.CIRNO, -16452865, -1, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> DAIYOUSEI_SPAWN_EGG = REGISTRY.register("daiyousei_spawn_egg", () -> new ForgeSpawnEggItem(HikariNoSanyouseiModEntities.DAIYOUSEI, -1, -1, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> DESK = block(HikariNoSanyouseiModBlocks.DESK, HikariNoSanyouseiModTabs.TAB_HIKARISANYOUSEI);
	public static final RegistryObject<Item> BURNEDFRIEDEGG = REGISTRY.register("burnedfriedegg", () -> new BurnedfriedeggItem());
	public static final RegistryObject<Item> LOUKANKEN = REGISTRY.register("loukanken", () -> new LoukankenItem());
	public static final RegistryObject<Item> HAKUROUKENNEW = REGISTRY.register("hakuroukennew", () -> new HakuroukennewItem());
	public static final RegistryObject<Item> SKILL_MARISASTARDUSTREVERIE = REGISTRY.register("skill_marisastardustreverie", () -> new SkillMarisastardustreverieItem());
	public static final RegistryObject<Item> SKILL_MARISA_FINALSPARK = REGISTRY.register("skill_marisa_finalspark", () -> new SkillMarisaFinalsparkItem());
	public static final RegistryObject<Item> MINIHAKKERO_FINAL_SPARK = REGISTRY.register("minihakkero_final_spark", () -> new MinihakkeroFinalSparkItem());
	public static final RegistryObject<Item> MARISAS_DANMAKU_NOTES = REGISTRY.register("marisas_danmaku_notes", () -> new MarisasDanmakuNotesItem());
	public static final RegistryObject<Item> DANMAKUTEST_1 = REGISTRY.register("danmakutest_1", () -> new Danmakutest1Item());
	public static final RegistryObject<Item> CONFIGMP = REGISTRY.register("configmp", () -> new ConfigmpItem());
	public static final RegistryObject<Item> SKILL_MARISA_DARK_SPARK = REGISTRY.register("skill_marisa_dark_spark", () -> new SkillMarisaDarkSparkItem());
	public static final RegistryObject<Item> MINIHAKKERO_DARK_SPARK = REGISTRY.register("minihakkero_dark_spark", () -> new MinihakkeroDarkSparkItem());
	public static final RegistryObject<Item> MINIHAKKERO_DRAK_SPARK = REGISTRY.register("minihakkero_drak_spark", () -> new MinihakkeroDrakSparkItem());
	public static final RegistryObject<Item> LASERNORML = REGISTRY.register("lasernorml", () -> new LasernormlItem());
	public static final RegistryObject<Item> BIGLASER = REGISTRY.register("biglaser", () -> new BiglaserItem());
	public static final RegistryObject<Item> SPELLCARDLUNATICRAINDANMAKU = REGISTRY.register("spellcardlunaticraindanmaku", () -> new SpellcardlunaticraindanmakuItem());
	public static final RegistryObject<Item> SHANXINGDANMUCESHI = REGISTRY.register("shanxingdanmuceshi", () -> new ShanxingdanmuceshiItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties().tab(tab)));
	}
}
